# Generated by Django 3.0.5 on 2021-10-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_stream', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='subscription_id',
            new_name='stream_id',
        ),
    ]
