# Generated by Django 3.0.5 on 2021-10-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_stream', '0002_auto_20211013_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='subscription_id',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
